# Numpy Array
matrise/vektor

### Hente biblioteket

In [1]:
import numpy as np

### Opprette Array
---

#### Manuelt

In [9]:
a = np.array([1,2,6,9,29])
a

array([ 1,  2,  6,  9, 29])

In [10]:
b = np.sqrt(a)
b

array([1.        , 1.41421356, 2.44948974, 3.        , 5.38516481])

In [11]:
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('float64')

#### np.zeros
fyller en array med 0-er

In [18]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### np.ones
fyller en array med 1-er

In [20]:
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones(10)*np.pi

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

### np.arange

np.arange(fra, til, intervall)


In [46]:
x1 = np.arange(0,10,2)
x1

array([0, 2, 4, 6, 8])

**Samme på tradisjonelle pythonlister**

In [30]:
[x for x in range(0,10,2)]

[0, 2, 4, 6, 8]

### np.linspace
np.arange(fra, til og med, antall elementer)



In [43]:
np.linspace(0,8,5)

array([0., 2., 4., 6., 8.])

### Printe

In [47]:
print(a)

[ 1  2  6  9 29]


In [48]:
print(b)

[1.         1.41421356 2.44948974 3.         5.38516481]


In [55]:
for e in b:
    print(f'{e:.2f}')

1.00
1.41
2.45
3.00
5.39


### Funksjoner

In [59]:
def f(x):
    return x**2

In [66]:
x = np.array([1,2,6,9,29])
y = f(x)

In [67]:
print(y)

[  1   4  36  81 841]
